name: Docker Buildx

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Install Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Register Arm Executable
        run: docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
      - name: Use new builder
        run: |
          docker buildx create --name builder
          docker buildx use builder
      - name: Build and push
        run: |
          docker buildx build --push \
            --tag "${{secrets.DOCKERHUB_USER}}/sliding_puzzle:${GITHUB_SHA::8}" \
            --tag "${{secrets.DOCKERHUB_USER}}/sliding_puzzle:latest" \
            --platform linux/amd64,linux/arm/v7 .
